import { readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

const sourcePath = require.resolve('@formily/core/dist/formily.core.all.d.ts')
const outputPath = resolve(
  __dirname,
  'src/components/ReactionsSetter/formilyCoreDeclaration.ts'
)
const declaration = readFileSync(sourcePath, 'utf8')

writeFileSync(
  outputPath,
  `/* eslint-disable */\n// Generated by generate-declarations.ts.\nconst declaration: string = ${JSON.stringify(
    declaration
  )}\n\nexport default declaration\n`
)
